spring:
  cloud:
    vault:
      enabled: false
    gateway:
      routes:
        - id: test-route
          uri: https://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mediaflow
  data:
    redis:
      host: localhost
      port: 6379
