spring:
  cloud:
    vault:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mediaflow
    username: mediaflow
    password: secret
  data:
    redis:
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mediaflow
